#ifndef PINS_H
#define PINS_H

#include <avr/io.h>
#include "arduino.h"

#define CONCAT(x,y)			x ## y

#define DDR(x)				CONCAT(DDR,x)
#define PORT(x)				CONCAT(PORT,x)
#define PIN(x)				CONCAT(PIN,x)

#define LED					ARDUINO_A0
#define LED_LINE			ARDUINO_A0_LINE

#define PCM2705_DPLUS		ARDUINO_D10
#define PCM2705_DPLUS_LINE	ARDUINO_D10_LINE

#define PCM2705_MD			ARDUINO_D11
#define PCM2705_MD_LINE		ARDUINO_D11_LINE
#define PCM2705_MC			ARDUINO_D12
#define PCM2705_MC_LINE		ARDUINO_D12_LINE
#define PCM2705_MS			ARDUINO_D13
#define PCM2705_MS_LINE		ARDUINO_D13_LINE

#define RC5					D
#define RC5_LINE			(1<<1)

/* Buttons definitions */
#define BUTTON_0			ARDUINO_D7
#define BUTTON_0_LINE		ARDUINO_D7_LINE
#define BUTTON_1			ARDUINO_D6
#define BUTTON_1_LINE		ARDUINO_D6_LINE
#define BUTTON_2			ARDUINO_D5
#define BUTTON_2_LINE		ARDUINO_D5_LINE
#define BUTTON_3			ARDUINO_D4
#define BUTTON_3_LINE		ARDUINO_D4_LINE
#define BUTTON_4			ARDUINO_D3
#define BUTTON_4_LINE		ARDUINO_D3_LINE
#define BUTTON_5			ARDUINO_D2
#define BUTTON_5_LINE		ARDUINO_D2_LINE
#define BUTTON_6			ARDUINO_D1
#define BUTTON_6_LINE		ARDUINO_D1_LINE

#endif /* PINS_H */
